version: '3.8'
services:
 app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fueltrack-app
    container_name: fuettrack
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /fueltrack-app

 mysql-db:
    image: mysql
    container_name: mysql_db2
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fueltrack
      MYSQL_ROOT_PASSWORD: hassan
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql






#  pma:
#         image: phpmyadmin:5.1
#         environment:
#             - PMA_ARBITRARY=1
#             - PMA_HOST=${DB_HOST}
#             - PMA_USER=${DB_USERNAME}
#             - PMA_PASSWORD=${DB_PASSWORD}
#             - PMA_PORT=${DB_PORT}
#         depends_on:
#             - database
#         ports:
#             - 8888:80


















#  webserver:
#     image: nginx:alpine
#     container_name: webserver
#     restart: unless-stopped
#     tty: true
#     ports:
#       - "80:80"
#       - "443:443"


# version: '2'

# services:
#   mariadb:
#     image: docker.io/bitnami/mariadb:10.6
#     environment:
#       # ALLOW_EMPTY_PASSWORD is recommended only for development.
#       - ALLOW_EMPTY_PASSWORD=yes
#       - MARIADB_USER=bn_myapp
#       - MARIADB_DATABASE=bitnami_myapp
#   myapp:
#     image: docker.io/bitnami/laravel:9
#     ports:
#       - '8000:8000'
#     environment:
#       - DB_HOST=mariadb
#       - DB_PORT=3306
#       - DB_USERNAME=bn_myapp
#       - DB_DATABASE=bitnami_myapp
#     volumes:
#       - './my-project:/app'
#     depends_on:
#       - mariadb











# version: '3.8'
# services:
#   db:
#     image: mysql:8.0
#     cap_add:
#       - SYS_NICE
#     restart: always
#     environment:
#       - MYSQL_DATABASE=quotes
#       - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
#     ports:
#       - '3306:3306'
#     volumes:
#       - db:/var/lib/mysql
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
# volumes:
#   db:
#     driver: local
